<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<module category="" descriptorversion="1.0" entrypoint="callThisModule/Start" forcesubdialogcall="false" frameworkversion="07.01.08.04" iconlarge="icons/defaultapplicationlg.gif" iconsmall="icons/defaultapplicationsm.gif" modifyInputs="false" modifyOutputs="false" nature="com.avaya.sce.core.speechnature" outputmultipart="false" paramasnamelist="false" provider="" submitmethod="get" version="1.0.0" webname="callThisModule">
    <description/>
    <input defaultvalue="" description="" name="testInput1" varreftypesimple="true"/>
    <output defaultvalue="" description="" name="testOutput" varreftypesimple="true"/>
    <language name="english" root="en-us"/>
    <dependencies/>
</module>
